server.port: 8091

spring:
  application:
    name: so
  sleuth:
    baggage:
      correlation-fields: random-int
      local-fields: random-int
      tag-fields: random-int
    sampler.probability: 1.0
  zipkin:
    base-url: http://localhost:9411
