server.port: 8082

spring:
  application.name: config-client
  config.import: configserver:http://localhost:8888
  cloud:
    config:
      username: config-server-user
      password: config-server-password