spring:
  application.name: stream-kafka

  cloud:
    function.definition: randomNumber;measurementCelsius;measurementFahrenheit;fahrenheitSink;fahrenheitFluxSink;failingConsumer
    stream:
      kafka:
        binder.brokers: localhost:9092
        bindings:
          failingConsumer-in-0:
            consumer:
              enableDlq: true
              max-attempts: 2
      bindings:
        randomNumber-out-0:
          destination: random-number-topic
        measurementCelsius-out-0:
          destination: measurements-celsius
        measurementFahrenheit-in-0:
          destination: measurements-celsius
        measurementFahrenheit-out-0:
          destination: measurements-fahrenheit
        fahrenheitSink-in-0:
          destination: measurements-fahrenheit
        fahrenheitFluxSink-in-0:
          destination: measurements-fahrenheit
        fromBridge-out-0:
          destination: arbitrary
        failingConsumerSender-out-0:
          destination: failing-consumer
        failingConsumer-in-0:
          destination: failing-consumer
          group: failing-consumer-group

logging:
  pattern:
    console: "%d{MM-dd HH:mm:ss} %5p - [%15.15t] %-25.25logger{25}: %m%n%wEx"